fix overlapping menu
nextcloud/nextcloud-dialogs pull request #423
Opened 2021-08-17 13:07 UTC by szaimen

Fix https://github.com/nextcloud/server/issues/26518
Signed-off-by: szaimen <szaimen@e.mail.de>

2021-08-18 14:44 UTC, juliushaertl requested changes

2021-08-18 14:44 UTC, juliushaertl commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
This will cause a regression with modals as the 10100 value was introduced in https://github.com/nextcloud/nextcloud-dialogs/pull/236 to fix that

2021-08-18 15:16 UTC, szaimen commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
for which modals would this apply?

2021-08-18 15:34 UTC, juliushaertl commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
Any modal from the vue library for example: viewer, firstrunwizard, settings dialogs

2021-08-18 15:37 UTC, szaimen commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
So in this case do you see a way to fix this https://github.com/nextcloud/server/issues/26518 at all?

2021-08-19 10:27 UTC, juliushaertl commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
> So in this case do you see a way to fix this nextcloud/server#26518 at all?

Can't think of a proper way currently. The issue is that the modal should overlap all content (also the header menus) while the toast should still be overlapped by the menus.

> maybe can we move the toasts a bit to the left? so that it doesn't overlap anymore with the menu?

Also not a solution as the menu has a dynamic width depending on the translations and the same issue also exists for the other popovers like search.

2021-09-20 13:19 UTC, jancborchardt commented
Design-wise it looks good! But yeah, Julius’ feedback is valid :)

2021-09-20 13:31 UTC, szaimen commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
Is there maybe a way to have the z-index for the fialogs by default on 2000 and simply increase it to 10100 when the modal opens and decrease it again when it gets closed?

2022-07-21 09:02 UTC, nickvergessen commented on styles/toast.scss
> +	z-index: 2000; // Needs to be below Nextcloud menu entries see https://github.com/nextcloud/server/issues/26518
> Is there maybe a way to have the z-index for the dialogs by default on 2000 and simply increase it to 10100 when the modal opens and reset it again when it gets closed?

Not sure how that would solve anything. Notifications e.g. is a popup just like in the screenshot, but the toasts triggered from it should overlap the popup. So the library can not solve this. In the case above we should:
1. Make sure the quota error is only shown once
2. The user should use the close button to navigate to the menu.

2022-10-28 09:16 UTC, skjnldsv commented
What is the status here?
We have 4.0.0 major on the line, in case this needs to get in as a breaking change :)

2022-10-28 09:17 UTC, szaimen commented
> What is the status here? We have 4.0.0 major on the line, in case this needs to get in as a breaking change :)

It can be closed as this is not fixable here.

2022-10-28 09:17 UTC, closed without merging

2022-10-28 09:22 UTC, skjnldsv commented
Thanks for the update @szaimen :)